service:
  name: cu
  port: 8080

news:
  api:
    url: https://newsapi.org/v2/top-headlines
    key: ${NEWS_API_KEY:dummy-api-key}
    cache:
      ttl: 60
  
spring:
  redis:
    host: ${NEWS_REDIS_HOST:localhost}
    port: ${NEWS_REDIS_PORT:6379}
    password: ${NEWS_REDIS_PASSWORD:dummy-password}
  
logging:
  level:
    org.springframework.cache: TRACE
    
